# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sma <- function(x, window_size, recentre = TRUE, miss = "single") {
    .Call(`_filters_sma`, x, window_size, recentre, miss)
}

ema <- function(x, alpha, miss = "reset") {
    .Call(`_filters_ema`, x, alpha, miss)
}

hampel <- function(x, window_size, a = 3.0, k = 1.4826, recentre = TRUE, miss = "single") {
    .Call(`_filters_hampel`, x, window_size, a, k, recentre, miss)
}

